languageCode = "en-us"
title = "DCRDEX | Cryptocurrency Exchange"
baseurl = "https://dex.decred.org/"

[params]
  # Site image and description used to populate og tags.
  images = ["/og-card.png"]
  description = "DCRDEX is an open source, peer-to-peer cryptocurrency exchange built by the Decred Project."

  # Bison Wallet URLs
  win_bisonw_installer_url  = "https://github.com/decred/dcrdex/releases/download/v1.0.0/bisonw-windows-amd64-v1.0.0.msi"
  win_bisonw_binary_url     = "https://github.com/decred/dcrdex/releases/download/v1.0.0/bisonw-tray-windows-amd64-v1.0.0.zip"
  mac_bisonw_installer_url  = "https://github.com/decred/dcrdex/releases/download/v1.0.0/bisonw-darwin-amd64-v1.0.0.dmg"
  mac_bisonw_binary_url     = "https://github.com/decred/dcrdex/releases/download/v1.0.0/bisonw-darwin-amd64-v1.0.0.tar.gz"
  mac_bisonw_binary_arm_url = "https://github.com/decred/dcrdex/releases/download/v1.0.0/bisonw-darwin-arm64-v1.0.0.tar.gz"
  lin_bisonw_binary_url     = "https://github.com/decred/dcrdex/releases/download/v1.0.0/bisonw-linux-amd64-v1.0.0.tar.gz"
  lin_bisonw_deb_url        = "https://github.com/decred/dcrdex/releases/download/v1.0.0/bisonw-debian-amd64-v1.0.0.deb"
  lin_bisonw_arm_url        = "https://github.com/decred/dcrdex/releases/download/v1.0.0/bisonw-linux-arm64-v1.0.0.tar.gz"

  # Decrediton URLs
  win_decrediton_url = "https://github.com/decred/decred-binaries/releases/download/v1.8.1/decrediton-v1.8.1.exe"
  mac_decrediton_url = "https://github.com/decred/decred-binaries/releases/download/v1.8.1/decrediton-amd64-v1.8.1.dmg"
  m1_decrediton_url  = "https://github.com/decred/decred-binaries/releases/download/v1.8.1/decrediton-arm64-v1.8.1.dmg"
  lin_decrediton_url = "https://github.com/decred/decred-binaries/releases/download/v1.8.1/decrediton-v1.8.1.AppImage"
  tar_decrediton_url = "https://github.com/decred/decred-binaries/releases/download/v1.8.1/decrediton-v1.8.1.tar.gz"
  dexreleases_url    = "https://github.com/decred/dcrdex/releases/tag/v1.0.0"
  umbrel_community_app_store_url = "https://github.com/decred/umbrel-app-store"
